import manifest from './manifest.json';

// manifest.json is generated by scripts/build-packs.mjs from the published zips.
export const PACK_HEADER = 'X-Codemarkets-Pack';

type Manifest = { agents_md_version: string; packs: Record<string, Record<string, string>> };
const m = manifest as Manifest;

export const agentsMdVersion = m.agents_md_version;

export function parseVersion(v: string): number[] | null {
  const match = /^(\d{1,4})\.(\d{1,4})\.(\d{1,4})$/.exec(v);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : null;
}

export function compareVersions(a: string, b: string): number {
  const [x, y] = [parseVersion(a)!, parseVersion(b)!];
  return x[0] - y[0] || x[1] - y[1] || x[2] - y[2];
}

export function packNames(): string[] {
  return Object.keys(m.packs).sort();
}

// Maps version to SHA-256 of the zip, or undefined for unknown packs.
export function packVersions(name: string): Record<string, string> | undefined {
  return m.packs[name];
}

export function latestVersion(name: string): string | undefined {
  return Object.keys(m.packs[name] ?? {}).sort(compareVersions).at(-1);
}
